name: Release Module

on:
  release:
    types: [created]
jobs:
  npm:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install npm dependencies
      run: npm ci

    - name: Test and build package
      run: |
        npm test
        npm run build
    - name: Publish tag to npm
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'